# Lazy jobs running on master post merges.
name: lazy
on: push
# TODO    branches: [master]

jobs:
  coverage:
    name: Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Generate report
        uses: actions-rs/tarpaulin@v0.1
        with:
          args: '--tests --all-features'
      - name: Upload to codecov.io
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Archive code coverage results
        uses: actions/upload-artifact@v1
        with:
          name: code-coverage-report
          path: cobertura.xml
  parse-dota2:
    name: Parse Dota2 shaders
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - run: mkdir data
      - name: Download shaders
        run: curl https://user.fm/files/v2-5573e18b9f03f42c6ae53c392083da35/dota2-shaders.zip -o data/all.zip
      - name: Unpack shaders
        run: cd data && unzip all.zip
      - name: Build Naga
        run: cargo build --release --features spv-in,msl-out --bin naga
      - name: Convert shaders
        run: for file in data/*.spv ; do echo "Translating" ${file} && target/release/naga --validate 27 ${file} ${file}.metal; done
  parse-vulkan-tutorial-shaders:
      name: Parse Sascha Willems Vulkan tutorial shaders
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: actions-rs/toolchain@v1
          with:
            profile: minimal
            toolchain: stable
        - name: Download shaders
          run: https://github.com/SaschaWillems/Vulkan.git
        - name: Build Naga
          run: cargo build --release --all-features --bin naga
        - name: Convert metal shaders
          run: |
            find "Vulkan/data/shaders/glsl/" -name '*.spv' | while read fname;
            do
                echo "Convert: $fname"
                target/release/naga --validate ${file} ${file}.metal
            done
