# Lazy jobs running on master post merges.
name: lazy
on: push
# TODO    branches: [master]

jobs:
  parse-vulkan-tutorial-shaders:
      name: Parse Sascha Willems Vulkan tutorial shaders
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: actions-rs/toolchain@v1
          with:
            profile: minimal
            toolchain: stable
        - name: Download shaders
          run: git clone https://github.com/SaschaWillems/Vulkan.git
        - name: Build Naga
          run: cargo build --release --all-features --bin naga
        - name: Convert metal shaders
          run: |
            touch counter
            SUCCESS_RESULT_COUNT=0
            FILE_COUNT=0
            find "Vulkan/data/shaders/glsl/" -name '*.spv' | while read fname;
            do
                echo "Convert: $fname"
                FILE_COUNT=$((FILE_COUNT+1))
                target/release/naga --validate "${file}" "${file}.metal" | true
                SUCCESS_RESULT_COUNT=$((SUCCESS_RESULT_COUNT + $?))
                echo "Success: $SUCCESS_RESULT_COUNT/$FILE_COUNT" > counter
            done
            cat counter
