name: validation-macos
on:
  push:
    paths:
    - 'tests/out/*.msl'
  pull_request:
    paths:
    - 'tests/out/*.msl'

jobs:
  validate-macos:
    name: MSL
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: make validate-msl
